# Generated by Django 4.2.3 on 2023-08-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0003_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing Address'), ('S', 'Shipping Address')], default='S', max_length=1),
        ),
    ]
