# Generated by Django 4.2.3 on 2023-08-09 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_website', '0005_address_phone_number_address_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=18, null=True)),
                ('expiry_date', models.DateField(max_length=18, null=True)),
                ('cvc', models.IntegerField(null=True)),
                ('account_title', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=90, null=True)),
                ('country', models.CharField(max_length=90, null=True)),
                ('state', models.CharField(max_length=90, null=True)),
                ('city', models.CharField(max_length=90, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
