# Generated by Django 4.2.3 on 2023-08-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0007_alter_paymentmethod_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_id',
            new_name='size',
        ),
    ]
