# Generated by Django 4.2.3 on 2023-08-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0009_remove_product_color_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='color',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='size',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
