# Generated by Django 4.2.3 on 2023-08-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0011_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
    ]
