# Generated by Django 4.2.3 on 2023-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0012_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('NP', 'Brand new product'), ('UP', 'Used product')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
