# Generated by Django 4.2.3 on 2023-08-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0014_alter_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercart',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.size'),
            preserve_default=False,
        ),
    ]
