# Generated by Django 4.2.3 on 2023-08-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0015_alter_usercart_color_alter_usercart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.color'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.size'),
        ),
    ]
